POST http://localhost:28090/api/v1.0/login
Content-Type : application/json

{
    "mobile":"0202000000",
    "password":"Th*mas024"
}

GET http://localhost:28090/api/v1.0/tasks
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.d2VsY29tZSB0byBhdGVuYSBubGE.a7WjEalx1ITQ4ayajg1EcGxOQnpSUNbA8LP9lbhqUgg

{
    "mobile":"0202000000",
    "password":"Th*mas024"
}


POST http://localhost:28090/api/v1.0/device
Content-Type : application/json

{
  "sender":"ATMoney",
  "data":"Dear Customer, your current ATMoney balance is GHS 8.60.Available Balance: GHS 8.60.",
  "action":"SMS",
  "simslot":"0",
  "mobile":"",
  "device_id":"052e75b8e3662840",
  "device_name":"Infinix X665",
  "mobile0":"233570026033",
  "mobile1":"",
  "slot0":"tigo gh",
  "slot1": "mtn gh"
}